#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

#swagger:
#  enabled: true
#  # host: mc-gateway:9999
#  title: 'Custom Test Service API'
#  description: 'Custom 接口文档'
#  version: '1.0.0'
#  authorization:
#    name: OAuth Server
#    auth-regex: ^.*$
#    authorization-scope-list:
#      - scope: server
#        description: server all
#    token-url-list:
#      - http://mc-gateway:9999/auth/oauth/token
#  base-path: /**
#  path-mapping: /
#  exclude-path:
#    - /actuator/**
#    - /error